name: "Check admin PR"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [trigger-ci]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-admin
  cancel-in-progress: true

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  BRANCH_NAME: ${{ github.ref }}

jobs:
  install-dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.11
      - name: Confirming everything is OK
        run: |
          ls -la venv

  unittests:
    name: Unittests
    runs-on: ubuntu-latest
    timeout-minutes: 7
    needs: [ install-dependencies ]
    env:
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_AUTHOR: ${{ github.actor }}